export const ICON_LIST = [
  { name: "Add Circle Bold", file: "Add-Circle-Bold.svg" },
  { name: "Alarm Bell Ring", file: "Alarm-Bell-Ring.svg" },
  { name: "Alert Bell Notification", file: "Alert-Bell-Notification-2.svg" },
  { name: "Alert Octagon", file: "Alert-Octagon-1.svg" },
  { name: "Ampersand", file: "Ampersand.svg" },
  { name: "Arrange Letter", file: "Arrange-Letter.svg" },
  { name: "Arrange List Descending", file: "Arrange-List-Descending.svg" },
  { name: "Arrange Number Descending", file: "Arrange-Number-Descending.svg" },
  { name: "Attachment", file: "Attachment.svg" },
  { name: "Bill Cross", file: "Bill-Cross.svg" },
  { name: "Bin 1", file: "Bin-1.svg" },
  { name: "Binocular", file: "Binocular.svg" },
  { name: "Blood Bag Cross", file: "Blood-Bag-Cross.svg" },
  { name: "Book Close Bookmark", file: "Book-Close-Bookmark-1.svg" },
  { name: "Book Open Bookmark", file: "Book-Open-Bookmark.svg" },
  { name: "Bookmark Cancel Delete", file: "Bookmark-Cancel-Delete.svg" },
  { name: "Bookmarks Document", file: "Bookmarks-Document.svg" },
  { name: "Branch Line", file: "Branch-Line-5.svg" },
  { name: "Brightness", file: "Brightness.svg" },
  { name: "Button Fast Forward", file: "Button-Fast-Forward-1.svg" },
  { name: "Button Loop", file: "Button-Loop.svg" },
  { name: "Button Play", file: "Button-Play.svg" },
  { name: "Button Stop", file: "Button-Stop.svg" },
  { name: "Button Zigzag", file: "Button-Zigzag-1.svg" },
  { name: "Calendar", file: "Calendar-3.svg" },
  { name: "Calendar Edit", file: "Calendar-Edit-1.svg" },
  { name: "Cell Border Frame", file: "Cell-Border-Frame.svg" },
  { name: "Check Badge", file: "Check-Badge.svg" },
  { name: "Check Double", file: "Check-Double.svg" },
  { name: "Check Square", file: "Check-Square.svg" },
  { name: "Checklist", file: "Checklist.svg" },
  { name: "Checkup Chart", file: "Checkup-Chart.svg" },
  { name: "Coding Apps Website", file: "Coding-Apps-Website-Web-Form-Text-Area-1.svg" },
  { name: "Cog Hand Give", file: "Cog-Hand-Give-1.svg" },
  { name: "Cog Search", file: "Cog-Search-1.svg" },
  { name: "Cog", file: "Cog.svg" },
  { name: "Command Button Keyboard", file: "Command-Button-Keyboard.svg" },
  { name: "Cursor Hand", file: "Cursor-Hand-2.svg" },
  { name: "Cursor Speed", file: "Cursor-Speed-2.svg" },
  { name: "Cursor Target", file: "Cursor-Target-1.svg" },
  { name: "Cursor", file: "Cursor.svg" },
  { name: "Delete 2", file: "Delete-2.svg" },
  { name: "Delete", file: "Delete.svg" },
  { name: "Diagnostic Desktop", file: "Diagnostic-Desktop.svg" },
  { name: "Dial Finger", file: "Dial-Finger-1.svg" },
  { name: "Dial Pad", file: "Dial-Pad.svg" },
  { name: "Direction Button 2", file: "Direction-Button-2.svg" },
  { name: "Direction Button 3", file: "Direction-Button-3.svg" },
  { name: "Division Math Symbol", file: "Division-Math-Symbol-Circle.svg" },
  { name: "Duplicate", file: "Duplicate.svg" },
  { name: "Equal Math Symbol", file: "Equal-Math-Symbol-Circle.svg" },
  { name: "Expand 2", file: "Expand-2.svg" },
  { name: "Expand Full", file: "Expand-Full.svg" },
  { name: "Face ID", file: "Face-Id-1.svg" },
  { name: "Filter", file: "Filter-1.svg" },
  { name: "Filter Sort Lines", file: "Filter-Sort-Lines-Descending.svg" },
  { name: "Gauge Dashboard", file: "Gauge-Dashboard.svg" },
  { name: "Hand Drag", file: "Hand-Drag.svg" },
  { name: "Hospital Building Pin", file: "Hospital-Building-Pin.svg" },
  { name: "Hospital Sign", file: "Hospital-Sign.svg" },
  { name: "Insurance Hand", file: "Insurance-Hand.svg" },
  { name: "Insurance Head", file: "Insurance-Head.svg" },
  { name: "Iris Scan", file: "Iris-Scan-1.svg" },
  { name: "Lab Tube Experiment", file: "Lab-Tube-Experiment.svg" },
  { name: "Lab Tube", file: "Lab-Tube.svg" },
  { name: "Lock Shield", file: "Lock-Shield.svg" },
  { name: "Lock Unlock", file: "Lock-Unlock-4.svg" },
  { name: "Login Key", file: "Login-Key.svg" },
  { name: "Medical App Laptop", file: "Medical-App-Laptop-1.svg" },
  { name: "Medical Specialty Knee", file: "Medical-Specialty-Knee-1.svg" },
  { name: "Megaphone", file: "Megaphone.svg" },
  { name: "Multiple Users", file: "Multiple-Users-1.svg" },
  { name: "Multiple Users Network", file: "Multiple-Users-Network.svg" },
  { name: "Paper Write", file: "Paper-Write.svg" },
  { name: "Pen Write", file: "Pen-Write.svg" },
  { name: "Pencil", file: "Pencil-1.svg" },
  { name: "Petri Dish", file: "Petri-Dish-2.svg" },
  { name: "Plus One Increment", file: "Plus-One-Increment.svg" },
  { name: "Radioactive Circle", file: "Radioactive-Circle.svg" },
  { name: "Radiology Scan Doctor", file: "Radiology-Scan-Doctor.svg" },
  { name: "Satellite", file: "Satellite.svg" },
  { name: "Science Molecule Structure", file: "Science-Molecule-Strucutre.svg" },
  { name: "Science Molecule", file: "Science-Molecule.svg" },
  { name: "Search Circle", file: "Search-Circle.svg" },
  { name: "Settings Slider Desktop", file: "Settings-Slider-Desktop-Horizontal.svg" },
  { name: "Share", file: "Share.svg" },
  { name: "Shrink", file: "Shrink.svg" },
  { name: "Skull", file: "Skull-1.svg" },
  { name: "Stopwatch", file: "Stopwatch.svg" },
  { name: "Synchronize Arrows", file: "Synchronize-Arrows-Three.svg" },
  { name: "Tags Favorite", file: "Tags-Favorite.svg" },
  { name: "Time Clock Fire", file: "Time-Clock-Fire.svg" },
  { name: "Time Daily", file: "Time-Daily-1.svg" },
  { name: "Tool Box", file: "Tool-Box.svg" },
  { name: "User Question", file: "User-Question.svg" },
  { name: "User Signal", file: "User-Signal-1.svg" },
  { name: "View Square", file: "View-Square.svg" },
  { name: "Voice ID Approved", file: "Voice-Id-Approved.svg" },
  { name: "Voice ID", file: "Voice-Id.svg" },
  { name: "Wifi Signal", file: "Wifi-Signal-2.svg" },
]
